write first tests; make add basic tests pass

diff --git a/env b/env
--- a/env
+++ b/env
@@ -2,19 +2,19 @@ export bin_install=""
 export app_install=""
 
 info() {
-    echo "[info]" $@
+    echo "[info]" $@ 1>&2
 }
 
 warn() {
-    echo "[warn]" $@
+    echo "[warn]" $@ 1>&2
 }
 
 success() {
-    echo "[success]" $@
+    echo "[success]" $@ 1>&2
 }
 
 error() {
-    echo "[error]" $@
+    echo "[error]" $@ 1>&2
     exit 1
 }
 
diff --git a/test/index b/test/index
--- a/test/index
+++ b/test/index
@@ -1,16 +1,35 @@
 #!/usr/bin/env bash
 
-main() {
-    mkdir sandbox
-    export sandbox=./sandbox
+run() {
+    local cmd=$@
     
-    if ! ./test/add "main" > /dev/null; then
-        echo "FAILED"
+    # make sandbox
+    mkdir -p "$cmd.sandbox"
+    export sandbox="$cmd.sandbox"
+    
+    # run test and report result
+    $cmd 2> "$cmd.log"
+    if [[ $? -eq 0 ]]; then
+        echo "PASS $cmd"
+        rm "$cmd.log"
+        rm -rf ${sandbox}
     else
-        echo "PASS"
+        echo "FAIL $cmd"
+        echo ">>>>>>>>"
+        echo "Output:"
+        echo ""
+        cat "$cmd.log"
+        echo ""
+        echo "Note: You can view this log at '$cmd.log'"
+        echo "Note: You can view the sandbox for this run at '$cmd.sandbox'"
+        echo "<<<<<<<<"
     fi
+}
 
-    rm -rf sandbox
+main() {
+    export -f run
+    
+    ./test/add main
 }
 
 main
